
[env:pico]

platform = raspberrypi
board = pico

upload_protocol = picotool

monitor_speed = 115200

build_type = debug

build_flags =
    -Iinclude
    -Ilib/FreeRTOS-Kernel/include
    -Ilib/FreeRTOS-Kernel/portable/GCC/ARM_CM0
    
    