[env:pico]
platform = raspberrypi
board = pico
upload_protocol = picotool
monitor_speed = 115200
build_type = debug

build_flags =
    -Iinclude
    -Ilib/FreeRTOS-Kernel/include
    -Ilib/FreeRTOS-Kernel/portable/ThirdParty/GCC/RP2040/include
    -Ilib/FreeRTOS-Kernel/portable/ThirdParty/GCC/RP2040
    -IC:/Users/jamaa/CO2-Control-System/build/generated/pico_base
    -IC:/Users/jamaa/pico-sdk/src/common/boot_picobin_headers/include
    -IC:/Users/jamaa/pico-sdk/src/common/boot_picoboot_headers/include
    -IC:/Users/jamaa/pico-sdk/src/common/boot_uf2_headers/include
    -IC:/Users/jamaa/pico-sdk/src/common/hardware_claim/include
    -IC:/Users/jamaa/pico-sdk/src/common/pico_base_headers/include
    -IC:/Users/jamaa/pico-sdk/src/common/pico_binary_info/include
    -IC:/Users/jamaa/pico-sdk/src/common/pico_bit_ops_headers/include
    -IC:/Users/jamaa/pico-sdk/src/common/pico_divider_headers/include
    -IC:/Users/jamaa/pico-sdk/src/common/pico_stdlib_headers/include
    -IC:/Users/jamaa/pico-sdk/src/common/pico_sync/include
    -IC:/Users/jamaa/pico-sdk/src/common/pico_time/include
    -IC:/Users/jamaa/pico-sdk/src/common/pico_usb_reset_interface_headers/include
    -IC:/Users/jamaa/pico-sdk/src/common/pico_util/include
    -IC:/Users/jamaa/pico-sdk/src/rp2_common/boot_bootrom_headers/include
    -IC:/Users/jamaa/pico-sdk/src/rp2_common/cmsis/include
    -IC:/Users/jamaa/pico-sdk/src/rp2_common/cmsis/stub/CMSIS/Core/Include
    -IC:/Users/jamaa/pico-sdk/src/rp2_common/cmsis/stub/CMSIS/Device/RP2040/Include
    -IC:/Users/jamaa/pico-sdk/src/rp2_common/cmsis/stub/CMSIS/Device/RP2350/Include
    -IC:/Users/jamaa/pico-sdk/src/rp2_common/hardware_adc/include
    -IC:/Users/jamaa/pico-sdk/src/rp2_common/hardware_base/include
    -IC:/Users/jamaa/pico-sdk/src/rp2_common/hardware_boot_lock/include
    -IC:/Users/jamaa/pico-sdk/src/rp2_common/hardware_clocks/include
    -IC:/Users/jamaa/pico-sdk/src/rp2_common/hardware_dcp/include
    -IC:/Users/jamaa/pico-sdk/src/rp2_common/hardware_divider/include
    -IC:/Users/jamaa/pico-sdk/src/rp2_common/hardware_dma/include
    -IC:/Users/jamaa/pico-sdk/src/rp2_common/hardware_exception/include
    -IC:/Users/jamaa/pico-sdk/src/rp2_common/hardware_flash/include
    -IC:/Users/jamaa/pico-sdk/src/rp2_common/hardware_gpio/include
    -IC:/Users/jamaa/pico-sdk/src/rp2_common/hardware_hazard3/include
    -IC:/Users/jamaa/pico-sdk/src/rp2_common/hardware_i2c/include
    -IC:/Users/jamaa/pico-sdk/src/rp2_common/hardware_interp/include
    -IC:/Users/jamaa/pico-sdk/src/rp2_common/hardware_irq/include
    -IC:/Users/jamaa/pico-sdk/src/rp2_common/hardware_pio/include
    -IC:/Users/jamaa/pico-sdk/src/rp2_common/hardware_pll/include
    -IC:/Users/jamaa/pico-sdk/src/rp2_common/hardware_powman/include
    -IC:/Users/jamaa/pico-sdk/src/rp2_common/hardware_psram/include
    -IC:/Users/jamaa/pico-sdk/src/rp2_common/hardware_pwm/include
    -IC:/Users/jamaa/pico-sdk/src/rp2_common/hardware_rcp/include
    -IC:/Users/jamaa/pico-sdk/src/rp2_common/hardware_resets/include
    -IC:/Users/jamaa/pico-sdk/src/rp2_common/hardware_riscv/include
    -IC:/Users/jamaa/pico-sdk/src/rp2_common/hardware_riscv_platform_timer/include
    -IC:/Users/jamaa/pico-sdk/src/rp2_common/hardware_rosc/include
    -IC:/Users/jamaa/pico-sdk/src/rp2_common/hardware_rtc/include
    -IC:/Users/jamaa/pico-sdk/src/rp2_common/hardware_sha256/include
    -IC:/Users/jamaa/pico-sdk/src/rp2_common/hardware_spi/include
    -IC:/Users/jamaa/pico-sdk/src/rp2_common/hardware_sync/include
    -IC:/Users/jamaa/pico-sdk/src/rp2_common/hardware_sync_spin_lock/include
    -IC:/Users/jamaa/pico-sdk/src/rp2_common/hardware_ticks/include
    -IC:/Users/jamaa/pico-sdk/src/rp2_common/hardware_timer/include
    -IC:/Users/jamaa/pico-sdk/src/rp2_common/hardware_uart/include
    -IC:/Users/jamaa/pico-sdk/src/rp2_common/hardware_vreg/include
    -IC:/Users/jamaa/pico-sdk/src/rp2_common/hardware_watchdog/include
    -IC:/Users/jamaa/pico-sdk/src/rp2_common/hardware_xip_cache/include
    -IC:/Users/jamaa/pico-sdk/src/rp2_common/hardware_xosc/include
    -IC:/Users/jamaa/pico-sdk/src/rp2_common/pico_aon_timer/include
    -IC:/Users/jamaa/pico-sdk/src/rp2_common/pico_async_context/include
    -IC:/Users/jamaa/pico-sdk/src/rp2_common/pico_atomic/include
    -IC:/Users/jamaa/pico-sdk/src/rp2_common/pico_bootrom/include
    -IC:/Users/jamaa/pico-sdk/src/rp2_common/pico_btstack/include
    -IC:/Users/jamaa/pico-sdk/src/rp2_common/pico_clib_interface/include
    -IC:/Users/jamaa/pico-sdk/src/rp2_common/pico_cxx_options/include
    -IC:/Users/jamaa/pico-sdk/src/rp2_common/pico_cyw43_arch/include
    -IC:/Users/jamaa/pico-sdk/src/rp2_common/pico_cyw43_driver/include
    -IC:/Users/jamaa/pico-sdk/src/rp2_common/pico_double/include
    -IC:/Users/jamaa/pico-sdk/src/rp2_common/pico_fix/rp2040_usb_device_enumeration/include
    -IC:/Users/jamaa/pico-sdk/src/rp2_common/pico_flash/include
    -IC:/Users/jamaa/pico-sdk/src/rp2_common/pico_float/include
    -IC:/Users/jamaa/pico-sdk/src/rp2_common/pico_i2c_slave/include
    -IC:/Users/jamaa/pico-sdk/src/rp2_common/pico_int64_ops/include
    -IC:/Users/jamaa/pico-sdk/src/rp2_common/pico_low_power/include
    -IC:/Users/jamaa/pico-sdk/src/rp2_common/pico_lwip/include
    -IC:/Users/jamaa/pico-sdk/src/rp2_common/pico_malloc/include
    -IC:/Users/jamaa/pico-sdk/src/rp2_common/pico_mbedtls/include
    -IC:/Users/jamaa/pico-sdk/src/rp2_common/pico_mem_ops/include
    -IC:/Users/jamaa/pico-sdk/src/rp2_common/pico_multicore/include
    -IC:/Users/jamaa/pico-sdk/src/rp2_common/pico_platform_common/include
    -IC:/Users/jamaa/pico-sdk/src/rp2_common/pico_platform_compiler/include
    -IC:/Users/jamaa/pico-sdk/src/rp2_common/pico_platform_panic/include
    -IC:/Users/jamaa/pico-sdk/src/rp2_common/pico_platform_sections/include
    -IC:/Users/jamaa/pico-sdk/src/rp2_common/pico_printf/include
    -IC:/Users/jamaa/pico-sdk/src/rp2_common/pico_rand/include
    -IC:/Users/jamaa/pico-sdk/src/rp2_common/pico_runtime/include
    -IC:/Users/jamaa/pico-sdk/src/rp2_common/pico_runtime_init/include
    -IC:/Users/jamaa/pico-sdk/src/rp2_common/pico_sha256/include
    -IC:/Users/jamaa/pico-sdk/src/rp2_common/pico_status_led/include
    -IC:/Users/jamaa/pico-sdk/src/rp2_common/pico_stdio/include
    -IC:/Users/jamaa/pico-sdk/src/rp2_common/pico_stdio_rtt/include
    -IC:/Users/jamaa/pico-sdk/src/rp2_common/pico_stdio_semihosting/include
    -IC:/Users/jamaa/pico-sdk/src/rp2_common/pico_stdio_uart/include
    -IC:/Users/jamaa/pico-sdk/src/rp2_common/pico_stdio_usb/include
    -IC:/Users/jamaa/pico-sdk/src/rp2_common/pico_thread_local/include
    -IC:/Users/jamaa/pico-sdk/src/rp2_common/pico_time_adapter/include
    -IC:/Users/jamaa/pico-sdk/src/rp2_common/pico_unique_id/include
    -IC:/Users/jamaa/pico-sdk/src/rp2_common/pico_usb_reset/include
    -IC:/Users/jamaa/pico-sdk/src/rp2_common/tinyusb/include
    -IC:/Users/jamaa/pico-sdk/src/rp2040/boot_stage2/include
    -IC:/Users/jamaa/pico-sdk/src/rp2040/hardware_regs/include
    -IC:/Users/jamaa/pico-sdk/src/rp2040/hardware_structs/include
    -IC:/Users/jamaa/pico-sdk/src/rp2040/pico_platform/include

lib_extra_dirs =
    lib

lib_deps =
    FreeRTOS-Kernel

