[env:pico]
platform = raspberrypi
board = pico
upload_protocol = picotool
monitor_speed = 115200
build_type = debug

build_flags =
    -Iinclude
    -Ilib/FreeRTOS-Kernel/include
    -Ilib/FreeRTOS-Kernel/portable/ThirdParty/GCC/RP2040/include
    -Ilib/FreeRTOS-Kernel/portable/ThirdParty/GCC/RP2040
    -IC:/Users/jamaa/pico-sdk/src/common/pico_stdlib_headers/include
    -IC:/Users/jamaa/pico-sdk/src/common/pico_base_headers/include
    -IC:/Users/jamaa/pico-sdk/src/rp2_common/hardware_uart/include
    -IC:/Users/jamaa/pico-sdk/src/rp2_common/hardware_gpio/include
    -IC:/Users/jamaa/pico-sdk/src/rp2_common/hardware_i2c/include
    -IC:/Users/jamaa/pico-sdk/src/rp2_common/hardware_timer/include
    -IC:/Users/jamaa/pico-sdk/src/rp2_common/hardware_flash/include
    -IC:/Users/jamaa/pico-sdk/src/rp2_common/hardware_sync/include
    -IC:/Users/jamaa/pico-sdk/src/rp2_common/hardware_exception/include
    -IC:/Users/jamaa/pico-sdk/src/rp2_common/hardware_base/include
    -IC:/Users/jamaa/pico-sdk/src/rp2040/hardware_structs/include

lib_extra_dirs =
    lib

lib_deps =
    FreeRTOS-Kernel